package org.example.mode.state;
/*
Generated by Open AI
 */
public class StateMainTest {
    public static void main(String[] args) {
        Room room = new Room(101);//房间号
        room.checkIn();//入住  房间变成有人状态
        room.clean();//入住期间不能打扫
        room.checkOut();//结账退房 房间变为打扫状态
        room.checkIn();//打扫期间不能入住
        room.clean();//打扫 房间变为空闲状态
        room.checkIn();//入住...
    }
}
