server:
  port: 8081
  servlet:
    context-path: /copy/mall

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall

mybatis:
  configuration:
    map-underscore-to-camel-case: true	#将下划线命名方式转换为驼峰命名
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

key:
  content:
    public-key-string: MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAi1yFQ9jBxvWXkriYn4I7tobrx3NQEIexs8U7DAhhbxlSbfTklaJeFCPhPKYXjQ4zYlCzDKtr2S2jD7jlez52BGIye3gQRU2WhWRL3f9ZxX3F/Gy6XjFncbgcPJNCH22M2zl+mSaGYOVVggyCT+Awh3NQsmgesnKggjAD/cBLkMVsULkwJjNNuIiT65PXVISthebDDGKfoWL3YTx6xxCkUMotCfRUwKsSq01oIyMm2l8bIHp3NtosnS/c9vtbzunGpVwnxfAoglteK0djnmEYshsEJ+wOKhs2TW3ouraLZqOyJIs6EucGVQe/1zeQwJkk8qr4mSg4mzUn/Hb3iDdHOe8i6oRfWYQ+c3ZUU3gCKufQe4NkOB9Rnd3v5Kh1Liu/b3VJIDQFvdP1SU+osA9DKp6qzjN7QSJXoCn+q4qazEl7EoGqUzd9q0F98JAEpi/bt+3jhAIASdmBl86KifLmyBQ7D8MPVSumbH/FdcvizYCEXGNRkLvQmTKr/08NC7pvAgMBAAE=
    private-key-string: MIIG/QIBADANBgkqhkiG9w0BAQEFAASCBucwggbjAgEAAoIBgQCLXIVD2MHG9ZeSuJifgju2huvHc1AQh7GzxTsMCGFvGVJt9OSVol4UI+E8pheNDjNiULMMq2vZLaMPuOV7PnYEYjJ7eBBFTZaFZEvd/1nFfcX8bLpeMWdxuBw8k0IfbYzbOX6ZJoZg5VWCDIJP4DCHc1CyaB6ycqCCMAP9wEuQxWxQuTAmM024iJPrk9dUhK2F5sMMYp+hYvdhPHrHEKRQyi0J9FTAqxKrTWgjIybaXxsgenc22iydL9z2+1vO6calXCfF8CiCW14rR2OeYRiyGwQn7A4qGzZNbei6totmo7IkizoS5wZVB7/XN5DAmSTyqviZKDibNSf8dveIN0c57yLqhF9ZhD5zdlRTeAIq59B7g2Q4H1Gd3e/kqHUuK79vdUkgNAW90/VJT6iwD0MqnqrOM3tBIlegKf6riprMSXsSgapTN32rQX3wkASmL9u37eOEAgBJ2YGXzoqJ8ubIFDsPww9VK6Zsf8V1y+LNgIRcY1GQu9CZMqv/Tw0Lum8CAwEAAQKCAYADlL0hNGNZ2qg9KZqgRQN3JVRWkH0jOXvBzthqqw+jS3ZPCzBNjcqvffpMepNKaFdj+CURNxIVDuRby2PDXuCK0h4VymrtjmBG/lLPODg2/rl18JvFAvjc1Q/3ReyajBP0EVXDQLKsZMoaUgHogqa0HUNeX+Fu/kMcA2nJMeQmuexw3YSj9ExMO6MmW8zaMXPjMzZ7zap+1TuDzBlgJkxam+yHeGUBAsRZEpQ3UFZdN7lphFOfAtPlxYcc8Xmr9iER/heKRfAhKu9+H/wCOPZ6JeqDzXWVMNnU4gGmd+tGvsUO987n5cI/kQnQVzLUETcpDkuQK9ClWzpZubLxOpzOdaYCtqAK3pW7SKFgXkwQqkKCllruMh+ET9t1UYW7yvY+ZCXRB5yzcVSYdLb53aVw5Svv6NAiOi7oIWugDvCNRfrBIC3/7n4yjByXjedimRFpo5/ywDfQ81wu9ReI0FOPJywT+Mn7eamKQQhnlhtY8Prvaa1g2l7HIj38G1ZTcZECgcEAvQ8rk1TUbvSxAeNDbMOHi3bJkUKYh1NRf2vBEYsD22OZUCEnym0FH/IoFsmZzPdMjVr0LM0XYnd4s/ZV8UY3D17mNBsGvUkKNt8/9sjN/meAqYjNtQSZHZAfnVNHofSxfY15F/9MdR7G+b+OlkM/fUWc2gVjqJ1tG/DIJiTsREyHD5GP4V/8LE7+abxwFS5XofK0PcqOicYElTaHNID8ZedKC8V9pyi97hHbJ7sQdWxJT0cSggs/vIaNGsFlKDTxAoHBALy0myxy7eC+L8ZXsHUI3DUymmkYxC29AyL+Bw6gPaXhyrBBNQcey4uZxXN0KIEfGDJoQltvATER5IXZ9um8zeu/Td3e0yd2nj5L9q3Gz+3kg1vvsHINcfCQl7cboJpeGWd+RdOh7079QfZaijo3SEZhQfCmbc0BjtxuwoW9lGNFeWKmsjPjJ9za9YrItPs9vVni9eXoJg+NyrtNDWUEOm6jE6Kyqcv3yCZDIBd3vgia6wR38sotcNk6AWSuVg1lXwKBwD4foQL9qfx3vT5QjlRL/9stAlkQGAzHrQ0AvGVmV7McjEFPU8LphfiUWuX6AubeEDKWw4uBLQD3HxuLg3wPxYHwfhZ7FwDV4lxbiaovG7lQC3Ap+uZTh3i2Zh0NQ4mNXVFTToo7IsWNgnaIonLv0An6+OqPQMskR7kZqrsWAOkEeJD+FNhK8RMiNelKuU3Md5FIrj9rsuDEx7a8PztacxWNJcCueXaXJan4BhqNFoBvP7ukMAm5Zo0tbWpwSCwpEQKBwQCIuh+YxClBZuv8vTqYgfP0A5dHwO8b6NCmAQMiAM7KK2CN9qEyaIi4vJEJR0e1zs7cbxhtYW+umzVGGpjB4NAfGTyVHsdF17dukeHJJb0wtBrNeU0SRlWhJVMYFEd4seecSizT24gmZm/tzMpMxhNzEzMQ57W1DYTyiLoe5y7mAsehyABkghk299tjVGt1gtV4lG7wxxUUvfr/XSPwZnDkCvrGLsfChuUZfBd7iYJCf+T7FuHuxZ/3dQTfa0XkbOcCgcAmAHTBioSOaQ+sEEo3yKexBzzhw2jM5masr25AQtri0WhmZkreGPabXfFgsx0hhHvJidp5R4Qz7nzdsk+bQ9f0rgAayIDOp88anzfIandyubBRThILHO+SfG50xEkZuq3cxC3pKvmKWBZTFtnmViUffZ9+cWQKJNxi29ZKnYlW5/Txgr2sgQyIygCFcMq3AX1zdbpV6gesJ0ixU4SB4hf3lgH4v9AuHOzFW8XHsryzq9Kjq4JOsgeIgYiR6cYlCFo=

aes:
  secret-key: xzIMtbp2+7WE3AlOWp0bwQ==
  init-vector: egjQOCODctkcUjeKxA8qDg==

jwt:
  secretKey: 'hello1234'  # 加密秘钥
  expireTime: 604800000   # 过期时间,7天
  tokenPrefix: 'Bearer ' # JWT令牌标识
  headerString: 'Authorization'

